version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_BASE=http://localhost:8000
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    depends_on:
      - backend
    restart: always